
INSERT INTO `permissions` (`id`, `title`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES
(1, 'مشاهده پوهنتون', 'view-university', 'user', NULL, NULL),
(2, 'ایجاد پوهنتون', 'create-university', 'user', NULL, NULL),
(3, 'تصحیح پوهنتون', 'edit-university', 'user', NULL, NULL),
(4, 'حذف پوهنتون', 'delete-university', 'user', NULL, NULL),
(5, 'مشاهده دیپارتمنت', 'view-department', 'user', NULL, NULL),
(6, 'ایجاد دیپارتمنت', 'create-department', 'user', NULL, NULL),
(7, 'تصحیح دیپارتمنت', 'edit-department', 'user', NULL, NULL),
(8, 'حذف دیپارتمنت', 'delete-department', 'user', NULL, NULL),
(9, 'مشاهده یوزر', 'view-user', 'user', NULL, NULL),
(10, 'ایجاد یوزر', 'create-user', 'user', NULL, NULL),
(11, 'تصحیح یوزر', 'edit-user', 'user', NULL, NULL),
(12, 'حذف یوزر', 'delete-user', 'user', NULL, NULL),
(13, 'مشاهده وظیفه', 'view-role', 'user', NULL, NULL),
(14, 'ایجاد وظیفه', 'create-role', 'user', NULL, NULL),
(15, 'تصحیح وظیفه', 'edit-role', 'user', NULL, NULL),
(16, 'حذف وظیفه', 'delete-role', 'user', NULL, NULL),
(17, 'مشاهده محصل', 'view-student', 'user', NULL, NULL),
(18, 'ایجاد محصل', 'create-student', 'user', NULL, NULL),
(19, 'تصحیح محصل', 'edit-student', 'user', NULL, NULL),
(20, 'حذف محصل', 'delete-student', 'user', NULL, NULL),
(24, 'مشاهده تبدیلی', 'view-transfer', 'user', NULL, NULL),
(25, 'ایجاد تبدیلی', 'create-transfer', 'user', NULL, NULL),
(26, 'حذف تبدیلی', 'delete-transfer', 'user', NULL, NULL),
(27, 'مشاهده منفکی', 'view-dropout', 'user', NULL, NULL),
(28, 'ایجاد منفکی', 'create-dropout', 'user', NULL, NULL),
(29, 'حذف منفکی', 'delete-dropout', 'user', NULL, NULL),
(30, 'مشاهده تاجیل', 'view-leave', 'user', NULL, NULL),
(31, 'ایجاد تاجیل', 'create-leave', 'user', NULL, NULL),
(32, 'حذف تاجیل', 'delete-leave', 'user', NULL, NULL),
(33, 'مشاهده استاد', 'view-teacher', 'user', NULL, NULL),
(34, 'ایجاد استاد', 'create-teacher', 'user', NULL, NULL),
(35, 'تصحیح استاد', 'edit-teacher', 'user', NULL, NULL),
(36, 'حذف استاد', 'delete-teacher', 'user', NULL, NULL),
(37, 'مشاهده کریکلم', 'view-curriculum', 'user', NULL, NULL),
(38, 'ایجاد کریکلم', 'create-curriculum', 'user', NULL, NULL),
(39, 'تصحیح کریکلم', 'edit-curriculum', 'user', NULL, NULL),
(40, 'حذف کریکلم', 'delete-curriculum', 'user', NULL, NULL),
(41, 'مشاهده اعلان', 'view-announcement', 'user', NULL, NULL),
(42, 'ایجاد اعلان', 'create-announcement', 'user', NULL, NULL),
(43, 'تصحیح اعلان', 'edit-announcement', 'user', NULL, NULL),
(44, 'حذف اعلان', 'delete-announcement', 'user', NULL, NULL),
(45, 'مشاهده گروپ', 'view-group', 'user', NULL, NULL),
(46, 'ایجاد گروپ', 'create-group', 'user', NULL, NULL),
(47, 'تصحیح گروپ', 'edit-group', 'user', NULL, NULL),
(48, 'حذف گروپ', 'delete-group', 'user', NULL, NULL),
(49, 'حذف پاسخ سوالات', 'delete-issues-comment', 'user', NULL, NULL),
(50, 'حذف سوالات', 'delete-issues', 'user', NULL, NULL),
(51, 'مشاهده صنف', 'view-course', 'user', NULL, NULL),
(52, 'ایجاد صنف', 'create-course', 'user', NULL, NULL),
(53, 'تصحیح صنف', 'edit-course', 'user', NULL, NULL),
(54, 'حذف صنف', 'delete-course', 'user', NULL, NULL),
(55, 'مشاهده لیست گروه', 'group-view-list', 'user', NULL, NULL),
(56, 'اضافه کردن محصل به گروه', 'group-add-student', 'user', NULL, NULL),
(57, 'حذف محصل از گروه', 'group-remove-student', 'user', NULL, NULL),
(58, 'تایید تاجیل', 'approve-leave', 'user', NULL, NULL),
(59, 'تایید منفکی', 'approve-dropout', 'user', NULL, NULL),
(60, 'تایید تبدیلی', 'approve-transfer', 'user', NULL, NULL),
(61, 'ایجاد گروه ها به شکل عمومی', 'create-all-groups', 'user', NULL, NULL),
(62, 'آبدیت عکس محصلان', 'update-student-photo', 'user', NULL, NULL),
(63, 'مشاهده لاگس', 'view-user-log', 'user', '2021-01-03 19:30:00', '2021-01-03 19:30:00'),
(64, ' پرنت ترانسکرپت', 'print-transcript', 'user', '2021-01-03 19:30:00', '2021-01-03 19:30:00'),
(65, 'ایحاد منفکی ها', 'create-all-dropout', 'user', '2021-01-03 19:30:00', '2021-01-03 19:30:00');

(66, 'مشاهده فارغین', 'view-graduated-student', 'user', NULL, NULL),
(67, 'ایجاد محصل فارغ', 'create-graduated-student', 'user', NULL, NULL),
(68, 'تصحیح محصل فارغ', 'edit-graduated-student', 'user', NULL, NULL),
(69, 'حذف محصل فارغ', 'delete-graduated-student', 'user', NULL, NULL),

(70, 'مشاهده فعالیت ها', 'view-activity_logs', 'user', NULL, NULL),
(71, 'نتایج سمستر وار', 'view-semester-base-result', 'user', NULL, NULL),
(72, 'چیک کردن نتایج سمستر وار', 'semester-base-result-check', 'user', NULL, NULL),
